---
- name: Post Vagrant Deploy - Environment Standardization
  hosts: localhost
  user: vagrant
  become: true

  tasks:

    - name: Get aptitude for upgrade
      apt: pkg=aptitude state=present

    - name: Safe system upgrade via aptitude
      apt: upgrade=safe

    - name: Add vim apt-repo
      apt_repository:
        repo: 'ppa:pi-rho/dev'

    - name: Install Packages
      apt: pkg={{item}} state=present update_cache=yes cache_valid_time=604800
      with_items:
        - git
        - python3.6
        - python-dev
        - python3-dev
        - python3.6-dev
        - python3.6-venv
        - build-essential
        - python3-pip
        - tmux
        - vim
        - cmake
        - python-software-properties
        - software-properties-common
        - vim-gtk

    - name: Alias pip3 to pip
      file:
        src: /usr/bin/pip3
        dest: /usr/bin/pip
        state: link

    - name: Install global python requirements
      pip: name={{item}} state=present
      with_items:
        - virtualenv
        - virtualenvwrapper
        - flake8  

    - name: Pulldown tmux config
      get_url:
        url: https://gist.githubusercontent.com/pezhore/23a8fa5174f59c7b56d70ff7cf02c372/raw/.tmux.conf
        dest: /etc/tmux.conf

    - name: Pulldown vim config
      get_url:
        url: https://gist.githubusercontent.com/pezhore/9e4a1333ac82a8bf41d9d529a3c4a88f/raw/.vimrc
        dest: /home/vagrant/.vimrc
        owner: vagrant
        group: vagrant

    - name: Pulldown bash_aliases
      get_url:
        url: https://gist.githubusercontent.com/pezhore/8f2bb97cecd2bc18e987a9fcafc6de33/raw/.bash_aliases
        dest: /home/vagrant/.bash_aliases
        owner: vagrant
        group: vagrant

    - name: Pulldown inputrc
      get_url:
        url: https://gist.githubusercontent.com/pezhore/776ca1b7a1d1cec8c33ed066e0deb1e2/raw/.inputrc 
        dest: /home/vagrant/.intputrc
        owner: vagrant
        group: vagrant

    - name: Pulldown bashrc
      get_url:
        url: https://gist.githubusercontent.com/pezhore/795d66c0cc628d184fc43c9f9889b8d3/raw/.bashrc
        dest: /home/vagrant/.bashrc
        owner: vagrant
        group: vagrant

    - name: Create vim autoload folder
      file:
        path: /home/vagrant/.vim/autoload
        state: directory
        owner: vagrant
        group: vagrant

    - name: Create vim bundle folder
      file:
        path: /home/vagrant/.vim/bundle
        state: directory
        owner: vagrant
        group: vagrant

    - name: Install Vundle
      git:
        repo: https://github.com/gmarik/Vundle.vim.git
        dest: /home/vagrant/.vim/bundle/Vundle.vim
      become_user: vagrant

    - name: install Git Bash Prompt
      git:
        repo: https://github.com/magicmonty/bash-git-prompt.git
        dest: /home/vagrant/.bash-git-prompt
        depth: 1
      become_user: vagrant

    - name: Install VIM plugins
      command: vim +PluginInstall +qall
      become_user: vagrant
    
    - name: Compile YouCompleteMe
      command: /home/vagrant/.vim/bundle/YouCompleteMe/install.py --clang-completer
      become_user: vagrant
